/**
 * Todo Api
 * Instructure Hungary Workshop Todo API  This API was created for the Kotlin Spring and Ruby on Rails workshops.  There is no user authentication yet in this version. You can use the global todo collection.  You can use the auto generated mock backend provided by SwaggerHub. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: henko@instructure.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TodoItem { 
    id: string;
    /**
     * Description of the task
     */
    title: string;
    /**
     * True if the task is already completed
     */
    completed?: boolean;
    createdAt?: Date;
    updatedAt?: Date;
    completedAt?: Date;
}